### ISSUE TITLE
编译报错 Unknown type name 'IOSurfaceRef'

### ISSUE THREAD

**Issue by liutongchao** [wf1992/WFRecScreenDemo#6]
Unknown type name 'IOSurfaceRef'

**Comment by wf1992** [comment]
如果你使用的是iOS 11 （Xcode9.0）以下的版本，请使用：
`CVReturn CVPixelBufferCreateWithIOSurface(
                                          CFAllocatorRef allocator,
                                          CFTypeRef surface,
                                          CFDictionaryRef pixelBufferAttributes,
                                          CVPixelBufferRef *pixelBufferOut);`

**Comment by wf1992** [comment]
In SRScreenRecorder.m  Line23.
如果你使用的是iOS 11 （Xcode9.0）以下的版本，请使用：
`CGImageRef UICreateCGImageFromIOSurface(CFTypeRef surface);
CVReturn CVPixelBufferCreateWithIOSurface(
                                          CFAllocatorRef allocator,
                                          CFTypeRef surface,
                                          CFDictionaryRef pixelBufferAttributes,
                                          CVPixelBufferRef *pixelBufferOut);`
